apiVersion: v1
kind: ConfigMap
metadata:
        name: padmin 
        namespace: wordpress-stack
        labels:
                apps.k8s.io/name: padmin
                apps.k8s.io/type: config
                apss.k8s.io/part-of: padmin
data:
        PMA_ABSOLUTE_URI: http://admin.dwsclass.io/phpmyadmin/
        PMA_HOST: mysql-service
        PMA_PORT: "3306"
        PMA_ARBITRARY: "1"

