apiVersion: v1
kind: ConfigMap
metadata:
        name: wpcm
        namespace: wordpress-stack
        labels:
                apps.k8s.io/name: wpcm
                apps.k8s.io/type: config
                apps.k8s.io/part-of: wpcm
data:
        WORDPRESS_DB_HOST: mysql-service
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_NAME: wpdb
